name = "Geeky"
license = "MIT"
licenselink = "https://github.com/gethugothemes/andromeda-light/blob/master/LICENSE"
description = "Materi Esemka merupakan website yang membahas semua materi di Sekolah Menengah Kejuruan"
homepage = "https://github.com/gethugothemes/geeky-hugo-startup-theme/"
demosite = "https://demo.gethugothemes.com/geeky/"
tags = ['blog', 'light', 'bootstrap', 'responsive', 'contact-form']
features = ['responsive']
min_version = "0.83.1"

[author]
name = "gethugothemes"
homepage = "https://gethugothemes.com/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5