############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "TIK"
url = "about/"
weight = 3
hasChildren = true

  [[main]]
  parent = "TIK"
  name = "Rekayasa Perangkat Lunak"
  url = "rekayasa-perangkat-lunak/"
  weight = 1

  [[main]]
  parent = "TIK"
  name = "Teknik Komputer dan Jaringan"
  url = "teknik-komputer-jaringan/"
  weight = 2

  [[main]]
  parent = "TIK"
  name = "Multimedia"
  url = "multimedia/"
  weight = 3

  [[main]]
  parent = "TIK"
  name = "Teknik Transmisi Telekomunikasi"
  url = "teknik-transmisi-telekomunikasi/"
  weight = 4


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2

[[footer]]
name = "Disclaimer"
url = "disclaimer/"
weight = 3

[[footer]]
name = "About"
url = "about/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5